config/routes.rb
Marketfinder::Application.routes.draw do
  resources :ratings

  devise_for :users
  
  resources :trips do
		resources :days do
      resources :rankings
    end
	end	

  resources :markets do
		collection{ post :import}
		get 'rankings', on: :member
	end

  post 'days/:id/sort' => 'days#sort'

	root 'trips#index'

  

end

app/models/trip.rb
class Trip < ActiveRecord::Base
	has_many :days
	has_and_belongs_to_many :users
	validates :name, :address, presence: true
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  	before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    	@trips = Trip.all
	end

	def show
		@days = @trip.days
		@local_address = @trip.address
		@markets = Market.near(@local_address, 10)
		fill_ratings
		fill_markers
	end

  def new
    @trip = Trip.new
  end

  def edit
  end

  def create
    @trip = current_user.trips.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trip }
      else
        format.html { render action: 'new' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:name, :description, :address)
    end

    def fill_markers
		@hash = Gmaps4rails.build_markers(@markets) do |market, marker|
			marker.lat market.latitude
			marker.lng market.longitude
			marker.infowindow market.description
			marker.title market.name
		end
	end
		
	def fill_ratings #For 'index'
		@ratings = Hash.new()
		@markets.each do |market|
			user_num = 0
			@ratings[market.id] = 0
			@days.each do |day|
				day.trip.users.each do |user|
					if add_score = user.ratings.where(market_id:market.id).first
						@ratings[market.id] += add_score.score
						user_num += 1
					end
					if user_num > 0
						@ratings[market.id] /= user_num
					end
				end
			end
		end
	end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/!locate.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

<div class="container">
	<div class="row row-offcanvas row-offcanvas-right">
		<div class="col-xs-12 col-sm-9">
			<div class="page-header">
				<h1>Trip Planner - <%= @trip.name %></h1>
			</div>
			<% @trips.each do |trip| %>
				<div class="row">
					<div class="col-md-6">
						<h3><%= trip.name %></h3>
						<table class="table table-hover">
						 <thead>
							<tr>
							 <th>Name</th>
							 <th>Description</th>
							 <th></th>
							</tr>
						 </thead>

						 <tbody>
							<% trip.markets.each do |market| %>
							 <tr>
								 <td><%= link_to market.name, market.website %></td>
								 <td><%= market.description %></td>
								 <td><%= image_tag(market.image, height:'100px') %></td>
							 </tr>
							<% end %>
						 </tbody>
						</table>
					</div>
				</div>
			<% end %>
		</div>	
		<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
			<ul class=list-group"><h3>Activities</h3>
				<% @markets.each do |market| %>
					<li class="list-group-item"><%=market.name%>: <%=market.description%></li>	
				<% end %>
			</ul>
		</div>
	</div>
	
	<hr>
	<div class="container">
		<div id="map" style="height:300px;" ></div>
	</div>
</div>

<script type="text/javascript">
	buildMap(<%=raw @hash.to_json %>);
</script>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, placeholder: "Name your trip." %>
  </div>
  <div class = "field">
    <%= f.label :address %><br>
    <%= f.text_field :address, placeholder: "We recommend using a zip code." %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, placeholder: "(Optional)" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
<% rownum = 1 %>
<div class="row col-m-12">
	<div class="page-header">
		<%= button_to "New Trip", new_trip_path, method: "get", class:"btn btn-primary btn-xs pull-right" %>
		<h1>Events</h1>
	</div>
	<% if notice %>
		<div class="alert alert-info alert-dismissiable">
			<p id="notice"><%= notice %></p>
		</div>
	<% end %>
</div>
<div class="row col-m-12">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Name</th>
				<th>Description</th>
			</tr>
		</thead>
		<tbody>
			<% @trips.each do |trip| %>
				<tr>
					<td>
						<h3><%= trip.name %> <%= link_to "(view)", trip_path(trip) %> <%= link_to "(edit)", edit_trip_path(trip) %></h3>
						<% trip.days.each do |day| %>
							<p><%= link_to day.name, trip_day_path(trip, day) %></p>
						<% end %>
					</td>
					<td width="478px;">
						<div id='reg_desc_<%=rownum%>'>
							<span id='desc_<%=rownum%>'><%= html_escape(trip.description).gsub(/\n/, '<br />').html_safe %></span><br/><br/><button type="button" data-rownum='<%= rownum %>' class="edit-description btn btn-default">Edit</button>
						</div>
						<div id='edit_desc_<%= rownum %>' style='display:none;'>
							<%= form_for trip, remote: true, html: {role: "form"} do |f| %>
								<%= f.text_area :description, rows: "10", class: "form-control enter-description"%> 
								<%= f.submit "Update", class:"btn btn-primary update-desc", data: {rownum:rownum}%>
							<% end %>
						</div>
					</td>
				</tr>
				<% rownum += 1 %>
			<% end %>
		</tbody>
	</table>
</div>

<script type="text/javascript">
	$(function(){
		$('.edit-description').click(function(){
			var rownum = $(this).attr("data-rownum");
			$('#reg_desc_'+rownum).toggle();
			$('#edit_desc_'+rownum).toggle();
		});

		$('.update-desc').click(function(){
			var rownum = $(this).attr("data-rownum");
			var desc = $(this).parent().children('.enter-description').val();
			$('#desc_'+rownum).html(desc.replace(/\n/g, "<br />"));
			$('#edit_desc_'+rownum).toggle();
			$('#reg_desc_'+rownum).toggle();
		});
	});
</script>

app/views/trips/locate.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

<div class="container">
	<div class="row row-offcanvas row-offcanvas-right">
		<div class="col-xs-12 col-sm-9">
			<div class="page-header">
				<h1>Trip Planner - Asheville, NC</h1>
			</div>
			<%= link_to "\"When you Get to Asheville\"", "http://www.youtube.com/watch?v=4RzhTN9zW3w", target: "blank"%>
			<% @trips.each do |trip| %>
				<div class="row">
					<div class="col-md-6">
						<h3><%= trip.name %></h3>
						<table class="table table-hover">
						 <thead>
							<tr>
							 <th>Name</th>
							 <th>Description</th>
							 <th></th>
							</tr>
						 </thead>

						 <tbody>
							<% trip.markets.each do |market| %>
							 <tr>
								 <td><%= link_to market.name, market.website %></td>
								 <td><%= market.description %></td>
								 <td><%= image_tag(market.image, height:'100px') %></td>
							 </tr>
							<% end %>
						 </tbody>
						</table>
					</div>
				</div>
			<% end %>
		</div>	
		<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
			<ul class=list-group"><h3>Activities</h3>
				<% @markets.each do |market| %>
					<li class="list-group-item"><%=market.name%>: <%=market.description%></li>	
				<% end %>
			</ul>
		</div>
	</div>
	
	<hr>
	<div class="container">
		<div id="map" style="height:300px;" ></div>
	</div>
</div>

<script type="text/javascript">
	buildMap(<%=raw @hash.to_json %>);
</script>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
<% rownum = 1 %>
<div class="row col-m-12">
	<div class="page-header">
		<h1><%=link_to "Events", root_path %> - <%= @trip.name %></h1>
	</div>
	<% if notice %>
		<div class="alert alert-info alert-dismissiable">
			<p id="notice"><%= notice %></p>
		</div>
	<% end %>
	<div class="btn-group">
		<%= link_to "Rate Activities", new_rating_path(rating:{trip_id: @trip.id}), class: "btn btn-primary", form_class: "pull-left" %>
		<%= link_to "Add Activities", new_market_path(trip_id: @trip.id), class: "btn btn-primary", style: "margin-left:5px" %>
		<%= link_to "Add a Day", new_trip_day_path(@trip), class: "btn btn-primary", style: "margin-left:5px" %>
	</div>
</div>
<div class="row col-m-12">
	<% @days.each do |day| %>
		<div class="row">
			<div class="col-md-12">
				<h3><%= day.name %> <%= link_to "(view)", trip_day_path(@trip, day) %></h3>
				<table class="table table-hover">
				 <thead>
					<tr>
					 <th></th>
					 <th>Name</th>
					 <th>Description</th>
					 <th></th>
					</tr>
				 </thead>

				 <tbody class="sortable">
					<% day.markets.each do |market| %>
					 <tr id='market_<%= market.id %>' class="ui-state-default" data-day_id='<%=day.id %>' >
						 <td class="handle"><%= image_tag("drag_arrow.png", width:'50px')%></td>
						 <td><%= link_to market.name, market.website %><br />
						 		<% i = 0 %>
								<% for i in 1..@ratings[market.id] %>	
									<%= image_tag("star.png", width:'15px') %>
								<% end %>	
								<% if i < market.rating %>
									<%= image_tag("star_half.png", width:'15px') %>
								<% end %>
						 </td>
						 <td width="478px;">
						 		<div id='reg_desc_<%=rownum%>'>
									<span id='desc_<%=rownum%>'><%= html_escape(market.description).gsub(/\n/, '<br />').html_safe %></span><br/><br/><button type="button" data-rownum='<%= rownum %>' class="edit-description btn btn-default">Edit</button>
								</div>
								<div id='edit_desc_<%= rownum %>' style='display:none;'>
									<%= form_for market, remote: true, html: {role: "form"} do |f| %>
										<%= f.text_area :description, rows: "10", class: "form-control enter-description"%> 
										<%= f.submit "Update", class:"btn btn-primary update-desc", data: {rownum:rownum}%>
									<% end %>
								</div>
						 </td>
						 <td>
						 	<%= image_tag(market.image, height:'300px') %>
						 </td>
					 </tr>
					<% rownum += 1 %>
					<% end %>
				 </tbody>
				</table>
			</div>
		</div>
	<% end %>
</div>	

<hr>
<div class="container">
	<div id="map" style="height:25em; width:100%;" >
	</div>
</div>

<script type="text/javascript">
	buildMap(<%=raw @hash.to_json %>);
	$(function(){
		$('.edit-description').click(function(){
			var rownum = $(this).attr("data-rownum");
			$('#reg_desc_'+rownum).toggle();
			$('#edit_desc_'+rownum).toggle();
		});

		$('.update-desc').click(function(){
			var rownum = $(this).attr("data-rownum");
			var desc = $(this).parent().children('.enter-description').val();
			$('#desc_'+rownum).html(desc.replace(/\n/g, "<br />"));
			$('#edit_desc_'+rownum).toggle();
			$('#reg_desc_'+rownum).toggle();
		});

		$('.sortable').sortable({
			dropOnEmpty: false,
			cursor: 'crosshair',
			handle: '.handle',
			items: 'tr',
			opacity: 0.4,
			scroll: true,
			revert: true,
			update: function(event, ui){
				var day_id = ui.item.attr('data-day_id');
				var market_id = ui.item.attr('data-market_id');
				$.ajax({
					data: $(this).sortable('serialize'),
					type: 'post',
					url: '/days/'+day_id+'/sort',
					dataType: 'script',
					complete: function(request){
						$('.sortable').effect('highlight');
					}
				});
			}
		});
	});
</script>