config/routes.rb
Marketfinder::Application.routes.draw do
  resources :ratings

  devise_for :users
  
  resources :trips do
		resources :days do
      resources :rankings
    end
	end	

  resources :markets do
		collection{ post :import}
		get 'rankings', on: :member
	end

  post 'days/:id/sort' => 'days#sort'

	root 'trips#index'

  

end

app/models/rating.rb
# == Schema Information
#
# Table name: ratings
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  market_id  :integer
#  created_at :datetime
#  updated_at :datetime
#  score      :integer
#

class Rating < ActiveRecord::Base
	before_save :default_values

	belongs_to :user
	belongs_to :market

	def default_values
		self.score ||= 0
	end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @trip = Trip.find(rating_params['trip_id'])
    @local_address = @trip.address
		@markets = Market.near(@local_address, 10).order(rating: :desc)
		i = 0
		begin
			@market = @markets[i]
			i += 1
		end while i < @markets.length() - 1 and current_user.ratings.where(market_id:@market.id).exists?
		if (@markets.length() == 0 ) or (i == @markets.length() - 1 and current_user.ratings.where(market_id: @market.id).exists?)
			redirect_to root_url, notice: "You've rated all activities near "+ @local_address+"!"
		else
    	@rating = Rating.new(score:0)
		end
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = current_user.ratings.create(score: params['score'], market_id: params['market'])
    render js: %(window.location.pathname='#{new_rating_path}')
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
	  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
 		 params.require(:rating).permit(:trip_id, :score, :user_id, :market_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<h1><%= @market.name %></h1>
	<div id="rating_frame">
		<%= image_tag @market.image, style: 'height:100%;' %>
		<p style="position:relative; top:-40px;">Yelp: <span id="star"></div></p>
		<div id="user_star" style="position:relative; top:-20px;"></div>
	</div>
<% end %>

app/views/ratings/edit.html.erb
<%= render 'form' %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<div class="container">
	<div class="page-header">
		<h1><%=link_to "Trip Planner", root_path %> - <%= @trip.name %></h1>
	</div>
<%= render 'form' %>
</div>
<script>
	$('#star').raty({
		size:50,
		readOnly: true,
		score: <%= @market.rating %>,
		path: '/assets'
	});

	$('#user_star').raty({
		size:50,
		score: <%= @rating.score %>,
		path: '/assets',
		click: function(score, evt) {
			$.ajax({
				url: '/ratings',
				method: 'post',
				data: { score: score, market: <%= @market.id %>, trip_id: <%= @trip.id %> }
			}).done(function (data){});
		}
	});
</script>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>