config/routes.rb
Marketfinder::Application.routes.draw do
  resources :ratings

  devise_for :users
  
  resources :trips do
		resources :days do
      resources :rankings
    end
	end	

  resources :markets do
		collection{ post :import}
		get 'rankings', on: :member
	end

  post 'days/:id/sort' => 'days#sort'

	root 'trips#index'

  

end

app/models/day.rb
# == Schema Information
#
# Table name: trips
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Day < ActiveRecord::Base
	belongs_to :trip
	has_many :rankings, -> { order("position DESC")}
	has_many :markets, through: :rankings
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  	before_action :set_day, only: [:show, :edit, :update, :destroy, :sort]
  	before_action :set_trip, only: [:create, :new, :show, :update, :destroy]

  	def new
    	@day = Day.new
  	end

  	def edit
	  	@trip = Trip.find(params['trip_id'])
  	end

	def show
		@local_address = @trip.address
		@markets = @day.markets
		fill_markers
		@markets = Market.near(@local_address, 10).order(name: :asc)
		fill_ratings2
	end

	def create
    	@day = @trip.days.new(day_params)

    	respond_to do |format|
	      	if @day.save
	        	format.html { redirect_to @trip, notice: 'Day was successfully created.' }
	        	format.json { render action: 'show', status: :created, location: @trip }
	      	else
	        	format.html { render action: 'new' }
	        	format.json { render json: @day.errors, status: :unprocessable_entity }
	      	end
    	end
  	end

  	def destroy
    	name = @day.name
    	@day.destroy
    	respond_to do |format|
      		format.html { redirect_to trip_path(@trip), notice: name + ' was successfully removed from ' + @trip.name + '.' }
      		format.json { head :no_content }
    	end
  	end

	def update
	    respond_to do |format|
	      if @day.update(day_params)
	        format.html { redirect_to trip_day_path(@trip, @day), notice: 'Day was successfully updated.' }
	        format.json { head :no_content }
	      else
	        format.html { render action: 'edit' }
	        format.json { render json: @day.errors, status: :unprocessable_entity }
	      end
	    end
  	end

#Unused

  	def index!
    	@days = @trip.days
		@local_address = @trip.address
		@markets = Market.near(@local_address, 10)
		fill_ratings	
		fill_markers
	end

	def sort!
		@sort_group = params['market'].reverse
		@markets = @day.markets
		@rankings = @day.rankings
		@rankings.each do |ranking|
			ranking.position = @sort_group.index(ranking.market_id.to_s) + 1
			ranking.save
		end
		render :nothing => true
	end

	def locate!
		@days = Day.all
		@local_address = "28801" #request.location.address
		@markets = Market.near(@local_address, 10) 
		fill_markers
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
    	@day = Day.find(params[:id])
    end

    def set_trip
		@trip = Trip.find(params[:trip_id])
	end

	def fill_markers
		@hash = Gmaps4rails.build_markers(@markets) do |market, marker|
			marker.lat market.latitude
			marker.lng market.longitude
			marker.infowindow market.description
			marker.title market.name
		end
	end
		
	def fill_ratings #For 'index'
		@ratings = Hash.new()
		@markets.each do |market|
			user_num = 0
			@ratings[market.id] = 0
			@trips.each do |trip|
				trip.users.each do |user|
					if add_score = user.ratings.where(market_id:market.id).first
						@ratings[market.id] += add_score.score
						user_num += 1
					end
					if user_num > 0
						@ratings[market.id] /= user_num
					end
				end
			end
		end
	end

	def fill_ratings2 #For 'show'
		@ratings = Hash.new()
		@markets.each do |market|
			user_num = 0
			@ratings[market.id] = 0
			@trip.users.each do |user|
				if add_score = user.ratings.where(market_id:market.id).first
					@ratings[market.id] += add_score.score
					user_num += 1
				end
				if user_num > 0
					@ratings[market.id] /= user_num
				end
			end
		end
	end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:name)
    end
end

app/views/days/!index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
<% rownum = 1 %>
<div class="container">
	<div class="row col-m-12">
		<div class="page-header">
			<h1>Trip Planner - <%= trip.name %></h1>
		</div>
		<% if notice %>
			<div class="alert alert-info alert-dismissiable">
				<p id="notice"><%= notice %></p>
			</div>
		<% end %>
		<%= link_to "\"When you Get to Asheville\"", "http://www.youtube.com/watch?v=4RzhTN9zW3w", target: "blank"%>
		<%= button_to "Rate Activities", new_rating_path, method: :get, class: "btn btn-primary" %>
	</div>
	<div class="row col-m-12">
		<% @days.each do |day| %>
			<div class="row">
				<div class="col-md-12">
					<h3><%= day.name %> <%= link_to "(view)", day_path(day) %></h3>
					<table class="table table-hover">
					 <thead>
						<tr>
						 <th></th>
						 <th>Name</th>
						 <th>Description</th>
						 <th></th>
						</tr>
					 </thead>

					 <tbody class="sortable">
						<% day.markets.each do |market| %>
						 <tr id='market_<%= market.id %>' class="ui-state-default" data-day_id='<%=day.id %>' >
							 <td class="handle"><%= image_tag("drag_arrow.png", width:'50px')%></td>
							 <td><%= link_to market.name, market.website %><br />
							 		<% i = 0 %>
									<% for i in 1..@ratings[market.id] %>	
										<%= image_tag("star.png", width:'15px') %>
									<% end %>	
									<% if i < market.rating %>
										<%= image_tag("star_half.png", width:'15px') %>
									<% end %>
							 </td>
							 <td width="478px;">
							 		<div id='reg_desc_<%=rownum%>'>
										<span id='desc_<%=rownum%>'><%= html_escape(market.description).gsub(/\n/, '<br />').html_safe %></span><br/><br/><button type="button" data-rownum='<%= rownum %>' class="edit-description btn btn-default">Edit</button>
									</div>
									<div id='edit_desc_<%= rownum %>' style='display:none;'>
										<%= form_for market, remote: true, html: {role: "form"} do |f| %>
											<%= f.text_area :description, rows: "10", class: "form-control enter-description"%> 
											<%= f.submit "Update", class:"btn btn-primary update-desc", data: {rownum:rownum}%>
										<% end %>
									</div>
							 </td>
							 <td>
							 	<%= image_tag(market.image, height:'300px') %>
							 </td>
						 </tr>
						<% rownum += 1 %>
						<% end %>
					 </tbody>
					</table>
				</div>
			</div>
		<% end %>
	</div>	
	
	<hr>
	<div class="container">
		<div id="map" style="height:25em; width:100%;" >
		</div>
	</div>
</div>

<script type="text/javascript">
	buildMap(<%=raw @hash.to_json %>);
	$(function(){
		$('.edit-description').click(function(){
			var rownum = $(this).attr("data-rownum");
			$('#reg_desc_'+rownum).toggle();
			$('#edit_desc_'+rownum).toggle();
		});

		$('.update-desc').click(function(){
			var rownum = $(this).attr("data-rownum");
			var desc = $(this).parent().children('.enter-description').val();
			$('#desc_'+rownum).html(desc.replace(/\n/g, "<br />"));
			$('#edit_desc_'+rownum).toggle();
			$('#reg_desc_'+rownum).toggle();
		});

		$('.sortable').sortable({
			dropOnEmpty: false,
			cursor: 'crosshair',
			handle: '.handle',
			items: 'tr',
			opacity: 0.4,
			scroll: true,
			revert: true,
			update: function(event, ui){
				var day_id = ui.item.attr('data-day_id');
				var market_id = ui.item.attr('data-market_id');
				$.ajax({
					data: $(this).sortable('serialize'),
					type: 'post',
					url: '/days/'+day_id+'/sort',
					dataType: 'script',
					complete: function(request){
						$('.sortable').effect('highlight');
					}
				});
			}
		});
	});
</script>

app/views/days/!locate.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

<div class="container">
	<div class="row row-offcanvas row-offcanvas-right">
		<div class="col-xs-12 col-sm-9">
			<div class="page-header">
				<h1>Trip Planner - <%= @trip.name %></h1>
			</div>
			<% @days.each do |day| %>
				<div class="row">
					<div class="col-md-6">
						<h3><%= day.name %></h3>
						<table class="table table-hover">
						 <thead>
							<tr>
							 <th>Name</th>
							 <th>Description</th>
							 <th></th>
							</tr>
						 </thead>

						 <tbody>
							<% day.markets.each do |market| %>
							 <tr>
								 <td><%= link_to market.name, market.website %></td>
								 <td><%= market.description %></td>
								 <td><%= image_tag(market.image, height:'100px') %></td>
							 </tr>
							<% end %>
						 </tbody>
						</table>
					</div>
				</div>
			<% end %>
		</div>	
		<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
			<ul class=list-group"><h3>Activities</h3>
				<% @markets.each do |market| %>
					<li class="list-group-item"><%=market.name%>: <%=market.description%></li>	
				<% end %>
			</ul>
		</div>
	</div>
	
	<hr>
	<div class="container">
		<div id="map" style="height:300px;" ></div>
	</div>
</div>

<script type="text/javascript">
	buildMap(<%=raw @hash.to_json %>);
</script>

app/views/days/_form.html.erb
<%= form_for([@trip, @day]) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>
<%= button_to 'Delete', trip_day_path(@trip, @day), method: :delete, class: 'btn btn-danger' %>
<hr>
<%= link_to 'Show', trip_day_path(@trip, @day) %> |
<%= link_to 'Back', trip_path(@trip) %>

app/views/days/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
<% rownum = 1 %>
<div class="container">
	<div class="row col-m-12">
		<div class="page-header">
			<h1>Trip Planner - <%= trip.name %></h1>
		</div>
		<% if notice %>
			<div class="alert alert-info alert-dismissiable">
				<p id="notice"><%= notice %></p>
			</div>
		<% end %>
		<%= link_to "\"When you Get to Asheville\"", "http://www.youtube.com/watch?v=4RzhTN9zW3w", target: "blank"%>
		<%= button_to "Rate Activities", new_rating_path, method: :get, class: "btn btn-primary" %>
	</div>
	<div class="row col-m-12">
		<% @days.each do |day| %>
			<div class="row">
				<div class="col-md-12">
					<h3><%= day.name %> <%= link_to "(view)", day_path(day) %></h3>
					<table class="table table-hover">
					 <thead>
						<tr>
						 <th></th>
						 <th>Name</th>
						 <th>Description</th>
						 <th></th>
						</tr>
					 </thead>

					 <tbody class="sortable">
						<% day.markets.each do |market| %>
						 <tr id='market_<%= market.id %>' class="ui-state-default" data-day_id='<%=day.id %>' >
							 <td class="handle"><%= image_tag("drag_arrow.png", width:'50px')%></td>
							 <td><%= link_to market.name, market.website %><br />
							 		<% i = 0 %>
									<% for i in 1..@ratings[market.id] %>	
										<%= image_tag("star.png", width:'15px') %>
									<% end %>	
									<% if i < market.rating %>
										<%= image_tag("star_half.png", width:'15px') %>
									<% end %>
							 </td>
							 <td width="478px;">
							 		<div id='reg_desc_<%=rownum%>'>
										<span id='desc_<%=rownum%>'><%= html_escape(market.description).gsub(/\n/, '<br />').html_safe %></span><br/><br/><button type="button" data-rownum='<%= rownum %>' class="edit-description btn btn-default">Edit</button>
									</div>
									<div id='edit_desc_<%= rownum %>' style='display:none;'>
										<%= form_for market, remote: true, html: {role: "form"} do |f| %>
											<%= f.text_area :description, rows: "10", class: "form-control enter-description"%> 
											<%= f.submit "Update", class:"btn btn-primary update-desc", data: {rownum:rownum}%>
										<% end %>
									</div>
							 </td>
							 <td>
							 	<%= image_tag(market.image, height:'300px') %>
							 </td>
						 </tr>
						<% rownum += 1 %>
						<% end %>
					 </tbody>
					</table>
				</div>
			</div>
		<% end %>
	</div>	
	
	<hr>
	<div class="container">
		<div id="map" style="height:25em; width:100%;" >
		</div>
	</div>
</div>

<script type="text/javascript">
	buildMap(<%=raw @hash.to_json %>);
	$(function(){
		$('.edit-description').click(function(){
			var rownum = $(this).attr("data-rownum");
			$('#reg_desc_'+rownum).toggle();
			$('#edit_desc_'+rownum).toggle();
		});

		$('.update-desc').click(function(){
			var rownum = $(this).attr("data-rownum");
			var desc = $(this).parent().children('.enter-description').val();
			$('#desc_'+rownum).html(desc.replace(/\n/g, "<br />"));
			$('#edit_desc_'+rownum).toggle();
			$('#reg_desc_'+rownum).toggle();
		});

		$('.sortable').sortable({
			dropOnEmpty: false,
			cursor: 'crosshair',
			handle: '.handle',
			items: 'tr',
			opacity: 0.4,
			scroll: true,
			revert: true,
			update: function(event, ui){
				var day_id = ui.item.attr('data-day_id');
				var market_id = ui.item.attr('data-market_id');
				$.ajax({
					data: $(this).sortable('serialize'),
					type: 'post',
					url: '/days/'+day_id+'/sort',
					dataType: 'script',
					complete: function(request){
						$('.sortable').effect('highlight');
					}
				});
			}
		});
	});
</script>

app/views/days/locate.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

<div class="container">
	<div class="row row-offcanvas row-offcanvas-right">
		<div class="col-xs-12 col-sm-9">
			<div class="page-header">
				<h1>Trip Planner - <%= @trip.name %></h1>
			</div>
			<% @days.each do |day| %>
				<div class="row">
					<div class="col-md-6">
						<h3><%= day.name %></h3>
						<table class="table table-hover">
						 <thead>
							<tr>
							 <th>Name</th>
							 <th>Description</th>
							 <th></th>
							</tr>
						 </thead>

						 <tbody>
							<% day.markets.each do |market| %>
							 <tr>
								 <td><%= link_to market.name, market.website %></td>
								 <td><%= market.description %></td>
								 <td><%= image_tag(market.image, height:'100px') %></td>
							 </tr>
							<% end %>
						 </tbody>
						</table>
					</div>
				</div>
			<% end %>
		</div>	
		<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
			<ul class=list-group"><h3>Activities</h3>
				<% @markets.each do |market| %>
					<li class="list-group-item"><%=market.name%>: <%=market.description%></li>	
				<% end %>
			</ul>
		</div>
	</div>
	
	<hr>
	<div class="container">
		<div id="map" style="height:300px;" ></div>
	</div>
</div>

<script type="text/javascript">
	buildMap(<%=raw @hash.to_json %>);
</script>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', trip_days_path(@trip) %>

app/views/days/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1><%=link_to "Events", root_path %> - <%= link_to @trip.name, @trip %></h1>
		</div>
	</div>
</div>
<div class="row row-offcanvas row-offcanvas-right">
	<div class="col-md-6">
		<% if notice %>
			<div class="alert alert-info alert-dismissiable">
				<p id="notice"><%= notice %></p>
			</div>
		<% end %>
		<h3><%= @day.name %> <%= link_to "(edit)", edit_trip_day_path(@trip, @day) %></h3>
		<table class="table table-hover">
		 <thead>
			<tr>
			 <th></th>
			 <th>Name</th>
			 <th>Description</th>
			 <th></th>
			 <th></th>
			</tr>
		 </thead>

		 <tbody class='sortable'>
			<% @day.markets.each do |market| %>
			 <tr id='market_<%= market.id %>' class="ui-state-default" data-day_id='<%=@day.id %>'>
				 <td class="handle"><%= image_tag("drag_arrow.png", width:'50px')%></td>
				 <td><%= link_to market.name, market.website %></td>
				 <td><%= market.description %></td>
				 <td><%= image_tag(market.image, height:'100px') %></td>
			 	 <td><%= button_to "Remove", trip_day_ranking_path(trip_id: @trip.id, day_id: @day.id, market_id: market.id), method: "delete", class:"btn btn-danger btn-xs" %></td>
			 </tr>
			<% end %>
		 </tbody>
		</table>
	</div>
	<div class="col-md-6 sidebar-offcanvas" id="sidebar" role="navigation">
		<ul class=list-group"><%= button_to "Add", new_market_path, method: "get", class:"btn btn-primary btn-xs pull-right" %>
		<h3>Activities</h3>
			<% @markets.each do |market| %>
				<% if !@day.markets.where(id: market.id).exists? %>
				<li class="list-group-item"><%= link_to(market.name, trip_day_rankings_path(@trip, @day, ranking:{day_id:@day.id, market_id: market.id}), method: "create") %>
					<% i=0 %>
					<% for i in 1..@ratings[market.id] %>	
						<%= image_tag("star.png", width:'15px') %>
					<% end %>	
					<% if i < market.rating %>
						<%= image_tag("star_half.png", width:'15px') %>
					<% end %>
				</li>
				<% end %>
			<% end %>
		</ul>
	</div>
</div>

<hr>

<div class="container">
	<div id="map" style="height:300px;" ></div>
</div>

<script type="text/javascript">
	buildMap(<%=raw @hash.to_json %>);
	
	$(function(){
		$('.sortable').sortable({
			dropOnEmpty: false,
			cursor: 'crosshair',
			items: 'tr',
			opacity: 0.4,
			scroll: true,
			handle: '.handle',
			revert: true,
			update: function(event, ui){
				var day_id = ui.item.attr('data-day_id');
				$.ajax({
					data: $(this).sortable('serialize'),
					type: 'post',
					url: '/days/'+day_id+'/sort',
					dataType: 'script',
					complete: function(request){
						$('.sortable').effect('highlight');
					}
				});
			}
		});
	});
</script>