config/routes.rb
Marketfinder::Application.routes.draw do
  resources :ratings

  devise_for :users
  
  resources :trips do
		resources :days do
      resources :rankings
    end
	end	

  resources :markets do
		collection{ post :import}
		get 'rankings', on: :member
	end

  post 'days/:id/sort' => 'days#sort'

	root 'trips#index'

  

end

app/models/market.rb
# == Schema Information
#
# Table name: markets
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  image       :string(255)
#  website     :string(255)
#  street      :string(255)
#  city        :string(255)
#  state       :string(255)
#  zip         :string(255)
#  latitude    :float
#  longitude   :float
#  created_at  :datetime
#  updated_at  :datetime
#  rating      :float
#

class Market < ActiveRecord::Base
	
	geocoded_by :full_address
	after_validation :geocode
	
	validates :name, presence: true

	has_many :rankings
	has_many :trips, through: :ranking
	has_many :ratings

	after_initialize :init

	def init
		self.rating ||= 0.0
	end
		
	def full_address
		"#{street}, #{city}, #{state} #{zip}"
	end

	def self.to_csv(options={})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |market|
				csv << market.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers:true) do |row|		
			market = find_by_id(row["id"]) || new
			market.attributes = row.to_hash
			market.save!
		end
	end
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_market, only: [:show, :edit, :update, :destroy]

  # GET /markets
  # GET /markets.json
  def index
    @markets = Market.all
		fill_markers
		respond_to do |format|
			format.html
			format.csv { send_data @markets.to_csv }
		end
  end

	def import
		Market.import(params[:file])
		redirect_to root_url, note: "Markets updated."
	end

	def locate
		@local_address = "28801" #request.location.address
		@markets = Market.near(@local_address, 10) 
		fill_markers
	end

  # GET /markets/1
  # GET /markets/1.json
  def show
  end

  # GET /markets/new
  def new
    @market = Market.new
  end

  # GET /markets/1/edit
  def edit
  end

  # POST /markets
  # POST /markets.json
  def create
    @market = Market.new(market_params)

    respond_to do |format|
      if @market.save
        format.html { redirect_to root_url, notice: 'Activity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @market }
      else
        format.html { render action: 'new' }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markets/1
  # PATCH/PUT /markets/1.json
  def update
    respond_to do |format|
      if @market.update(market_params)
        format.html { redirect_to @market, notice: 'Market was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markets/1
  # DELETE /markets/1.json
  def destroy
    @market.destroy
    respond_to do |format|
      format.html { redirect_to markets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market
      @market = Market.find(params[:id])
    end
		
		def fill_markers
			@hash = Gmaps4rails.build_markers(@markets) do |market, marker|
				marker.lat market.latitude
				marker.lng market.longitude
				marker.title market.name
			end
		end

    # Never trust parameters from the scary internet, only allow the white list through.
    def market_params
      params.require(:market).permit(:name, :website, :street, :city, :state, :zip, :latitude, :longitude, :description, :image, :rating)
    end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_form.html.erb
<%= form_for(@market, html: {role: "form"}) do |f| %>
  <% if @market.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@market.errors.count, "error") %> prohibited this market from being saved:</h2>

      <ul>
      <% @market.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows:"3"%>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :street %><br>
    <%= f.text_field :street, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.text_field :state, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :zip %><br>
    <%= f.text_field :zip, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, class: "form-control", placeholder: "(Optional)" %>
  </div>
  <div class="form-group">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, class: "form-control", placeholder: "(Optional)" %>
  </div>
 <div class="form-group">
    <%= f.label :image %><br>
    <%= f.text_field :image, class: "form-control", placeholder: "(Link to Image)" %>
  </div>
  <div class="form-group">
    <%= f.label :yelp_rating %><br>
    <%= f.number_field :rating, options={in: 0...6, step:0.5, class: "form-control"} %>
  </div>
  <div class="actions">
    <%= f.submit "Add Activity", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/markets/edit.html.erb
<h1>Editing market</h1>

<%= render 'form' %>

<%= link_to 'Show', @market %> |
<%= link_to 'Back', markets_path %>

app/views/markets/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<h1>Listing markets</h1>

<div>
  <table>
    <thead>
      <tr>
        <th>Name</th>
  			<th>Description</th>
        <th>Image</th>
        <th>Street</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @markets.each do |market| %>
        <tr>
          <td><%= link_to market.name, market.website %></td>
  				<td><%= market.description %></td>
          <td><%= image_tag market.image, style: "max-width:100px" %></td>
          <td><%= market.street %></td>
          <td><%= market.city %></td>
          <td><%= market.state %></td>
          <td><%= market.zip %></td>
          <td><%= market.latitude %></td>
          <td><%= market.longitude %></td>
          <td><%= link_to 'Show', market %></td>
          <td><%= link_to 'Edit', edit_market_path(market) %></td>
          <td><%= link_to 'Destroy', market, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div>
  <hr>
  <%= form_tag import_markets_path, multipart:true do%>
  	<%= file_field_tag :file %>
  	<%= submit_tag "Import" %>
  <% end %>
  <hr>
  <%= link_to "Export CSV", markets_path(format:"csv") %>
</div>
<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider:{}, internal: {id: 'map'}}, function(){
		markers = handler.addMarkers(<%=raw @hash.to_json %>);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();
	});
</script>

app/views/markets/locate.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<h1>Trip Planner - Asheville, NC</h1>

<div class="row">
	
	<div class="col-md-6">
		<div id="map" style="height:400px;" ></div>
	</div>

	<div class="col-md-6">
	<table>
 	 <thead>
 	  <tr>
     <th>Name</th>
     <th>Address</th>
 	  </tr>
 	 </thead>

 	 <tbody>
    	 <% @markets.each do |market| %>
      	 <tr>
        	 <td><%= link_to market.name, market.website %></td>
     		   <td><%= market.full_address %></td>
   		   </tr>
 		   <% end %>
 		 </tbody>
		</table>
	</div>

</div>

<br>

<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider:{}, internal: {id: 'map'}}, function(){
		markers = handler.addMarkers(<%=raw @hash.to_json %>);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();
		handler.addCircles(<%=raw @circles.to_json %>);
	});
</script>

app/views/markets/new.html.erb
<div class="container">
	<div class="col-md-12">
	<h1>New Activity</h1>

	<%= render 'form' %>

	<%= link_to 'Back', :back %>
	</div>
</div>

app/views/markets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @market.name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @market.website %>
</p>

<p>
  <strong>Street:</strong>
  <%= @market.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @market.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @market.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @market.zip %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @market.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @market.longitude %>
</p>

<p>
  <strong>Description:</strong>
  <%= @market.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@market.image) %>
</p>

<%= link_to 'Edit', edit_market_path(@market) %> |
<%= link_to 'Back', markets_path %>